### ISSUE TITLE
Add a real Slot in the Database

### ISSUE THREAD

**Issue by Theo-Hafsaoui** [wedidtln/sopra-project-LHD#62]
To realize the second User Story #20 we need to be able to add a Slot(done with #51) but also *connect*
this slot to associative table(Group_slot,Professor_slot).

To my mind we have two possibility:

 - first and simplest add an overload to existing save
```
 public void save ( Slot slot, Student student ) throws SQLException
 public void save ( Slot slot , Student student, Professor professor) throws SQLException
```
- the second is almost the same but new dao for this associative table and the connection done in the facade
```
 public static addSlot ( Slot slot, Student student ) 
 public void addSlot ( Slot slot , Student student, Professor professor)
```

I prefer the first one but the second would also make sense to me.

**Comment by Desmondmies** [comment]
overload existing save?
in my mind i would use save from SlotDao like it is
`public void save ( Slot slot ) throw SQLException`

and add in it, some code to make change for the corresponding associative table
The `Slot entity` already got :

- `private final List<Group> group`
- `private final List<Professor> professors`

So, just adding a bit of code in the save method to make changes to the associative table would do the trick,
then you only need to manipulate the slot object, which contains already everything you need,

Maybe add an helper function to get all slots associated to one student, something along those lines
`public List<Slot> getAllStudentSlots ( Student student ) ` inside StudentDAO.java maybe

And to clarify my idea for the group and professor associative table missing code inside SlotDAO (my fault btw),
It's already been done for the associative table `group_user in StudentDAO`

- `GET_ALL_GROUP Statement ( get all group inside group_user )`
- `SAVE_GROUP Statement ( save into group_user )`

**Comment by Theo-Hafsaoui** [comment]
Yeah forgot about the attribute of the entity slot. I guess that's the best solution

**Comment by anastygnome** [comment]
@Desmondmies Question is, should we do that manipulation in SlotDAO or in GroupDAO :  I see a call to GroupDAO when getting a slot, should we not put it there?

**Comment by Theo-Hafsaoui** [comment]
Aldready done in the facade, might be faster but not realy usefull... Maybe id you got time after fixing the CI

**Comment by Desmondmies** [comment]
@anastygnome i think it makes more sense to add it in GroupDAO, rather than SlotDAO
GroupDAO already got some code to add / update on the table group_slot i think and group_user

and the missing table is professor_slot, so maybe add some code as well in ProfessorDAO

so SlotDAO would use those Dao to make changes

**Comment by Theo-Hafsaoui** [comment]
I agree with @Desmondmies

**Comment by anastygnome** [comment]
> For the date it is aldready done in the facade, maybe it would be faster but not realy usefull... Maybe if you got time after fixing the CI

I mean, it's just a SQL WHERE clause, but I'll work on the CI beforehand.
